import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Simple Share",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="md:w-1/2 px-4 md:px-0 mx-auto font-mono">
        <nav className="flex flex-row md:items-center justify-between my-5 md:my-10 border-b border-b-gray-600 pb-3">
          <Link className="text-4xl font-bold uppercase" href={"/"}>Simple Share</Link>
          <Link className="text-white px-3 text-2xl bg-black font-medium p-2 rounded-md w-fit" href={"/posts/create"}>+</Link>
        </nav>
        <div>
        {children}
        </div>
        </section>
      </body>
    </html>
  );
}
